version: "3"

services:
  build:
    working_dir: /src
    image: golang
    command: make
    volumes:
      - .:/src
      - .cache/go:/go
    depends_on:
      - amqp
      - sql
    environment:
      GOPATH: /go:/src

  amqp:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  sql:
    image: postgres
    environment:
      POSTGRES_USER: gossip
      POSTGRES_PASSWORD: gossip
      POSTGRES_DB: gossip
    ports:
      - "5432:5432"
