version: "3"

services:
   mailserver:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

   app:
    image: node
    working_dir: /app
    volumes:
      - ".:/app"
    depends_on:
      - mailserver
    ports:
      - "9001:9000"
    environment:
      - "SMTP_HOST=mailserver"
      - "SMTP_PORT=1025"
    command: npm run start
